name: renalizapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auth_buttons: ^3.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.1
  dio: ^5.3.3
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_core_web: ^2.7.0
  firebase_database: ^10.2.5
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.4.2
  font_awesome_flutter: ^10.5.0
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  image_picker: ^1.0.4
  maps_launcher: ^2.2.0
  provider: ^6.0.5
  random_avatar: ^0.0.8
  shared_preferences: ^2.2.1
  whatsapp: ^0.0.1
  url_launcher: ^6.1.14
  file_picker: ^4.1.6


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/renalizapp_icon_noText.png

flutter:
  assets:
    - assets/renalizapp_icon.png
    - assets/renalizapp_icon_noText.png
    - .env
  uses-material-design: true
