name: renalizapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.5.0
  go_router: ^10.1.0
  auth_buttons: ^3.0.0
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5  
  google_fonts: ^5.1.0
  firebase_database: ^10.2.5
  firebase_core: ^2.15.1
  firebase_core_web: ^2.7.0
  http: ^1.1.0
  cloud_firestore: ^4.9.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/renalizapp_icon.png
    - .env
  uses-material-design: true
